name: Terraform Infra CI/CD

on:
  workflow_dispatch:

jobs:
  preprod-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init -backend-config="key=preprod.tfstate"
      - run: terraform plan -var-file=environments/preprod/terraform.tfvars -out=tfplan-preprod

  preprod-apply:
    needs: preprod-plan
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init -backend-config="key=preprod.tfstate"
      - run: terraform apply -auto-approve tfplan-preprod

  prod-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init -backend-config="key=prod.tfstate"
      - run: terraform plan -var-file=environments/prod/terraform.tfvars -out=tfplan-prod

  prod-apply:
    needs: prod-plan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init -backend-config="key=prod.tfstate"
      - run: terraform apply -auto-approve tfplan-prod
